name: Build and Push Docker Image To Docker Hub

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'Shared.net9/**'
      - 'Server.net9/**'
      - 'ConsoleGameServer/**'
      
permissions:
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zonakkis/goilauncher-multiplayer-console-server:latest
